title: Mintmintmintminto?
email: seokbong60@gmail.com
description: >-
  Do you linke mint? I like minto!
baseurl: ""
url: "http://127.0.0.1:4000"

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/